### ISSUE TITLE
Add OpsGenie as notifications system

### ISSUE THREAD

**Issue by panda87** [influxdb/kapacitor#71]
Please add output integration with OpsGenie.
If you need any help with their documentation or best practices for the API calls, just let me know.

D.

**Comment by nathanielc** [comment]
Kapacitor's alerting system is simple: 

It tracks the state of an alert one of OK,INFO,WARN,CRITICAL 
It calls registered alert handlers whenever the state is not OK or when it has just changed to the state OK from a non OK state.
Looking at the OpsGenie api it seems to have a Create/Close API calls which map to the alert entering and leaving a non OK state. What about for changes in state like WARN->CRITICAL?

Contributing the handler is pretty straight forward:

1. Create a new service in the `services` package and implement methods for interacting with OpsGenie.
2. Add the OpsGenie service to the `cmd/kapacitord/run` package so the server can open/close and configure the service.
3. Update the AlertNode in `pipeline` so the TICKscripts can declare OpsGenie options
4. Update the AlertNode in `kapacitor` to register the handler when configured via the TICKscript.
5. Update the TaskMaster to have an interface for communicating with the OpsGenie service.

You can follow the examples of Slack, PagerDuty, and VictorOps as they are all very similar.

**Comment by schmurfy** [comment]
instead of implementing every services out there that can receive alerts it would be wiser and easier to maintain to implement something flexible enough to allow doing it  directly in a user script. I imagine all these services have an http(s) endpoint and except some kind of parameters in the query or in the post body.

**Comment by nathanielc** [comment]
@schmurfy I agree that implementing every service out there will get out of hand. Right now it is easier to just implement them directly in Go instead of building a sandbox env to do so. Already the differences between the implemented services is enough that a simple HTTP POST template with URLs will not be sufficient. For now simplicity wins. That said the current organization of each Alert Handler will not scale and I am looking into ways to clean that up.
