### ISSUE TITLE
Question: re kapacitor vs continuous queries influxdb

### ISSUE THREAD

**Issue by danievanzyl** [influxdb/kapacitor#87]
Hi Guys,

Awesome product announcements. I would like to know, what would be the preferred way of aggregating data. I don't want to spend too much time developing continuous queries, if I can achieve same or maybe even better results with kapacitor.

Thanks for the hard work you guys have put into these products!

**Comment by nathanielc** [comment]
Some high level differences between Kapacitor and using CQs in InfluxDB:

* Kapacitor can do more than just store data back into InfluxDB, so if you ever plan to trigger an event etc off the aggregations I would start with Kapacitor.
* Kapacitor provides more flexible scheduling. ie. cron schedules versus just fixed periods.
* Kapacitor provides isolation. Using Kapacitor you can keep the heavy workload of computing aggregations off the InfluxDB database. Depending on scale this could be very important.
* Kapacitor is another failure point. If you are only planning on running a few aggregations then running another process to do so may be overkill.

Those are some high level differences. If you plan to rely heavily on aggregations then I would recommend Kapacitor, because it will be a more robust solution. That said, Kapacitor is a new product and if reliability is a hard requirement stick with CQs for now until Kapacitor has a few more releases under its belt.
