### ISSUE TITLE
Is there a task configuration RESTful API in kapacitor?

### ISSUE THREAD

**Issue by pootzko** [influxdb/kapacitor#90]
Hi,

I was wondering if something like configuring tasks in kapacitor through a REST API (something in the line of what you have in influxDB) is supported by kapacitor? If not - are you planning on supporting this?

One useful scenario for this is if you have a website which is a front-end to all the collected data and you would like to let users setup alerts of their own (if they need it).

Thanks

**Comment by nathanielc** [comment]
There is already a REST API for interacting with Kapacitor. It is undocumented at this time since we expect it to change as the API is very young. If you want to try it out the `kapacitor` command is really just a CLI wrapper on the HTTP API endpoints. You can find example usages of the API here https://github.com/influxdb/kapacitor/blob/master/cmd/kapacitor/main.go 

We plan to eventually document and commit to a stable API. We also see great potential in a front-end to manage tasks etc in Kapacitor. The plan is to keep Kapacitor simple and not provide a front-end out of the box but rather expose its functionality via the API so that a front-end could be built independently.

**Comment by pootzko** [comment]
Ok, thanks for the reply. I am asking because I both need this for the project I'm working on and because I would like to implement it into InfluxData.Net lib that I'm working on. So, this is good news. Thanks. :)
