### ISSUE TITLE
Reverse alerts

### ISSUE THREAD

**Issue by panda87** [influxdb/kapacitor#92]
In Riemann for example there is a feature that since it's always remove old data points to fit the ttl set for each service (metric name), it knows to recognize if new data point has not added and send an alert.
With this behave you can be alerted if server is down for example or in business aspect if you didn't get any transaction from the last x seconds, which can indicate on problem.

Do you think that Kapacitor can be used for the cases above?

D.

**Comment by nathanielc** [comment]
This is possible by monitoring the throughput of Kapacitor tasks.

Kapacitor emits stats about each task into the stream under the database _kapacitor.  A TICKscript like the following will trigger an alert if any stream tasks' throughput drops

```
stream
       .from().database('_kapacitor').measurement('edges')
       //grab only the stream tasks and the root node
       .where(lambda: "type" == 'stream' AND "parent" == 'stream0')
       .groupBy('task')
       .derivative('collected')
           .nonNegative()
       .window()
            .period(1m)
            .every(1m)
       .mapReduce(influxql.sum('collected'))
       .alert()
            .crit(lambda: "sum" < 100)
            ...
```
(the above is untested but you get the idea)

This TICKscript will take the last 60s of data per task and sum up the total number of points processed. If the total drops below 100, fire an alert.

Just define the above alert like so:

```
kapacitor define -name task_reverse_alert -type stream -dbrp _kapacitor.default -tick path/to/above/script 
```

By default internal stats are emitted every 10s into the stream under the database _kapacitor, see config for more details. 

This is a different approach than the index that Riemann uses but the throughput numbers are out-of-band from the data in the task itself. This allows for the reverse alert to not be adversely effected by performance of the task being monitored.

I find it useful to store the internal stats data in InfluxDB so that I can debug running tasks. I have a task like so running:

```
$ kapacitor show _stats
Name: _stats
Error:
Type: stream
Enabled: true
Executing: true
Databases Retention Policies: ["_kapacitor"."default"]
TICKscript:
stream
    .from()
    .influxDBOut()

```

**Comment by panda87** [comment]
Thanks you very much @nathanielc this was the best answer I could ask!
